### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by khuyentran1401** [datapane/gallery#1]
Client (0.4.6) and Provider (~=0.6.0) versions not compatible
![image](https://user-images.githubusercontent.com/49108771/84680974-1d4e9380-aef9-11ea-9264-8e225ac3b3ea.png)

**Comment by lanthias** [comment]
Thanks @khuyentran1401! This is because that version of the script was made with an incompatible version of the API. A new version should be available on the Readme of the start-up calculator script. 

We also recently added versioning, so stale URLs shouldn't be much of a problem going forwards!

**Comment by khuyentran1401** [comment]
Thank you for the fix. Got it to work!
